name: Build Craftable Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to use for the docker image
        default: 'latest'
        required: false
        type: string

jobs:
  build-craftable:
    permissions:
        packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: StrataSource/strata-ci-images/craftable
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: .
          dockerfile: ./craftable.Dockerfile
          tags: ${{ inputs.tag }}
